language: scala
scala:
- 2.10.3
env:
  global:
    - secure: BYg5M6wRItR9CtLDmOJzQMGaaxP6vgRcGvLyufkWi8pHrh0gTzqB3AmdS5BF3Auxji0jZqGUYktedWM5rNKPriYrn+h3yEIFu8ph8UIUGvl7ErYxc0ujEUzRH/IvwfEX9FAmG2hrEVj/kpSRQleWkQvshM3wW8aKiGvInKT0Z64=
    - secure: IBi7YGz4PeXuye+00cew+OpTvHn4qKftFwy5z1MEcSIHSTV4N2y3eVJ0pOmDEf27XvtqSJSLMAChCPjHFZ6UipZS9GAniDHMWlXFuKLWxeI2Lp+5958zS9otzKFHfp7+7G19V6nWrwl1HgRVMBdAVyHVLGkT4WZk7o+34kLkVug=
  matrix:
    - SAUCE_BROWSER=firefox
    - SAUCE_BROWSER=chrome
addons:
  sauce_connect: true
before_install:
  - sudo apt-get update
  - sudo apt-get -y install screen
install: true
before_script:
  - bash bin/start-container.sh
script:
  - ./sbt test
